baseURL: "https://aalavicena.github.io/avicena-pages/"
title: Naufal Rahman Avicena
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: /papers/
          weight: 1
        - name: About Me
          url: cv/
          weight: 3
    #    - name: Teaching
    #      url: courses/
    #      weight: 2
    #    - name: US Policy Rates
    #      url: policy/
    #      weight: 4
        - name: News
          url: news/
          weight: 4
        
##        - name: Newsletter
##          url: https://pmichaillat.substack.com
#          weight: 4

params:
    description: "I am a Master's student at Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Naufal Rahman Avicena
          subtitle: "Welcome! I am a Master's student at Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences.
           <br>  <br> I am currently working on understanding the drivers and outlook of elephant-caused human casualties across Tropical Asia. I am mainly trained as an ecologist (familiar with ecological modelling and has fieldwork experience), but have experience with AI application research (CNN, and more recently, NLP). Feel free to send an email to know more about me! "
          # <br>  <br> **I am on the 2024-2025 job market.**
          imageUrl: "https://raw.githubusercontent.com/aalavicena/avicena-pages/refs/heads/main/content/pic-300.jpg"
          imageWidth: 300
          imageHeight: 300
          imageTitle: Naufal Rahman Avicena
          buttons:
#            - name: Job Market Paper
#              url: papers/JMP_WeiZhang_Aug25.pdf            
            
            - name: Research
              url: papers/
#            - name: Teaching
#              url: courses/
            - name: About Me
              url: cv/
#            - name: US Policy Rates
#              url: policy/
            - name: News
              url: news/
#            - name: About Me
#              url: about/
#            - name: Newsletter
#              url: https://pmichaillat.substack.com
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
    socialIcons:
        - name: CV
          url: Content/CV-Naufal.pdf
        - name: Email
          url: mailto:naufalrahmanavicena@gmail.com
        - name: Location
          url: location/
#        - name: Office Hours
#          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=LzPzZhMAAAAJ&hl=en
#        - name: YouTube
#          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/aalavicena
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: Twitter
#          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Naufal Rahman Avicena"
      icon: /favicon-whale.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
